spring.application.name=RECUVA
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.url=jdbc://java_dbs:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/

spring.security.oauth2.client.registration.auth0.client-id=CcjHgGBkdkCszm0rt5mIO6jTPkOZ1YoD

spring.security.oauth2.client.registration.auth0.client-secret=K4uH7jIwhvTLyvereWyZKappswh3GlcjYQWH_ZoOCLMTm-pgQuJy0gAAXrTsCnan

spring.security.oauth2.client.registration.auth0.scope=openid,profile,email,offline_access,https://dev-ygztsimsgp6ywe30.us.auth0.com/roles
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0
spring.security.oauth2.client.registration.auth0.client-name=Auth0
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.provider=auth0


spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/authorize

spring.security.oauth2.client.provider.auth0.token-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/oauth/token

spring.security.oauth2.client.provider.auth0.jwk-set-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/.well-known/jwks.json

spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/userinfo

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/
#auth0.api.audience=https://api.recuva.com

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

