spring.application.name=RECUVA
#pring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.url=jdbc:postgresql://java_dbs:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Auth0 para el frontend (OAuth2 Client)
auth0.domain=dev-ygztsimsgp6ywe30.us.auth0.com
auth0.client-id=CcjHgGBkdkCszm0rt5mIO6jTPkOZ1YoD
auth0.client-secret=K4uH7jIwhvTLyvereWyZKappswh3GlcjYQWH_ZoOCLMTm-pgQuJy0gAAXrTsCnan
auth0.redirect-uri=http://localhost:8080/callback
auth0.issuer=https://dev-ygztsimsgp6ywe30.us.auth0.com/
auth0.jwks-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/.well-known/jwks.json

# Configuración de Auth0 para el backend (OAuth2 Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-ygztsimsgp6ywe30.us.auth0.com/

auth0.api.audience=https://api.recuva.com
